stages:
  build:
    buildTool: "mta"
    source: helloworldui5
    buildDescriptor: "mta.yaml"
    buildToolVersion: "MBTJ21N22"
  malwareScan:
    scan: false
  release:
    cfDeploy:
      strategy: "default"
      apiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
      org: "organ"
      space: "dev"
      credential: "btp"